ResourcePackLink: http://yoursite.com/rp.zip
ResourcePackRequestEnabled: true

GuiTitle: "&7   &Ha7b499» Настройка РП сервера «"

Messages:
  # Разрешения
  NoPermission:
    - "&cУ вас нет прав!"
  NotPlayer:
    - "&cКоманду может использовать только игрок!"

  # Перезагрузка
  ReloadInProgress:
    - ""
    - "&Hfc7d3e ⏳  &Hffab81|  &Hfc7d3eПерезагружаем конфиг..."
    - ""
  ReloadStart:
    - ""
    - "&Hfc7d3e ⏳  &Hffab81|  &Hfc7d3eПерезагружаем конфиг..."
    - ""
  ReloadFinish:
    - ""
    - "&H9dff6c ✔  &Hceffb6|  &Hceffb6Конфиг перезагружен успешно!"
    - ""

  PluginDisabled:
    - "&eПлагин выключен!"

KickMessages:
  - ""
  - ""
  - "&H343434*  *  *"
  - ""
  - "&Hff4836&lОшибка!"
  - "&7"
  - "&Hff9d89Чтобы зайти на сервер, вам необходимо"
  - "&Hff9d89согласиться на установку ресурспака!"
  - "&7"
  - "&H343434&m          &m"
  - "&7"
  - "&H9d9bbfЕсли это сообщение появляется, но у вас есть"
  - "&H9d9bbfнаш ресурспак, тогда обратитесь"
  - "&H9d9bbfв наш &H5b4dff&lDiscord &H9d9bbfсервер"
  - "&7"
  - "&7&Ha595ffhttps://riceodyssey.space/discord"
  - "&7"
  - "&H343434*  *  *"

SuccessMessages:
  - ""
  - "&H9dff6c ☀  &Hceffb6|  &Hceffb6Спасибо за установку нашего ресурспака!"
  - ""


GuiItems:
  SiteOnline:
    Name: '&7'
    Lore:
      - '&H5aff2d&l Ресурспак доступен &H5aff2d✔'
      - ''
      - '&7 &H8ea887Плагин успешно получает файлы с сайта, '
      - '&7 &H8ea887игроки могут спокойно скачивать'
      - '&7 &H8ea887ресурспак сервера.'
      - ''
      - '&7 &H2dc3ff● &lПлагин &H666360→ &H7de34a⓪ &lСайт &H666360→ &Hffce26◆ &l&nРесурспак&7 '
      - ''
  SiteOffline:
    Name: '&7'
    Lore:
      - '&Hff3333&l Ресурспак недоступен &Hff3333✘'
      - ''
      - '&7 &H8ea887Нет соединения с сайтом, проверьте сервер '
      - '&7 &H8ea887где расположен ваш ресурспак!'
      - ''
      - '&7 &H2dc3ff● &lПлагин &H666360→ &Hff3333&m⓪ &lСайт&H666360 &H666360→ &Hff3333&m◆ &lРесурспак&7 '
      - ''
  RPEnabled:
    Name: '&7'
    Lore:
      - ' &Hb3ff8bЗапрос ресурспака: &H5aff2d&lВКЛ &H5aff2d✔ '
      - ''
      - ' &H9caf92В данный момент, запрос набора ресурсов для игроков '
      - ' &H9caf92на сервере включен!'
      - ''
      - ' &Hdbffd5◆ Нажмите чтобы &Hff3535&lвыключить'
      - ''
  RPDisabled:
    Name: '&7'
    Lore:
      - ' &HffcfcfЗапрос ресурспака: &Hff3535&lВЫКЛ &Hff3535✘'
      - ''
      - ' &H9caf92В данный момент, запрос набора ресурсов для игроков,'
      - ' &H9caf92на сервере выключен!'
      - ''
      - ' &Hffd5d5◇ Нажмите чтобы &H5aff2d&lвключить'
      - ''
  ReloadItem:
    Name: '&7'
    Lore:
      - '&H5aff2d&l Перезагрузка конфига плагина &H5aff2d⏳ '
      - ''
      - '&H9caf92 ⚑ Нажмите, чтобы перезагрузить '
      - '&H9caf92 файл &H7bfa4b&l&nconfig.yml&7 '
      - ''
  ReloadingItem:
    Name: '&7'
    Lore:
      - '&Hf3fe4a  ☰ &lПерезагружаемся...  '
      - ''

#
#         *        .        ✦          .             .         *
#        .                *        .         ✷             ✧        .
#               .        ⋆    *         ✧         *      ⋆          .
#  ⋆           .        .        ⋆     .             ⋆       .     .
#        ✷         .       *         ✦     ⋆      .     ⋆      *
# .      ⋆    ⋆        .         ✧       ⋆     ✦           ⋆         ✦
#        .    ⋆         ✷             ⋆          ⋆    ✧      .      ⋆
# ✷      .        ⋆     .    ⋆      ☄       ⋆     .     ⋆     ✧        .
#       .    ✦       .      ⋆       ⋆      ✷        .        ⋆       .
#             ⋆        ⋆        ✷           .         ✦      ⋆
#  ⋆    .       ✦       ⋆       .     𝒷𝓎       ✷        ✦        ⋆       ✷
#       .         ✷        ⋆        𝓈𝓁𝓎𝓅𝒽  .         ✧    ⋆         ⋆
#   ✷          .        .      ⋆  𝒾𝓃 ２０２５  .             ⋆        .      .
#        .          ⋆    *         ✦         *      ⋆          .
#            .                *        .         ✷             ✧        .
#        ✷         .       *         ✦     ⋆      .     ⋆      *
# .      ⋆    ⋆        .         ✧       ⋆     ✦           ⋆         ✦
#        .    ⋆         ✷             ⋆          ⋆    ✧      .      ⋆
# ✷      .        ⋆     .    ⋆      ☄       ⋆     .     ⋆     ✧        .
#       .    ✦       .      ⋆       ⋆      ✷        .        ⋆      .
#             ⋆        ⋆        ✷           .         ✦      ⋆
#         *        .        ✦          .             .         *
#